### ISSUE TITLE
GitHub Actions is deprecating `set-env` and `add-path` commands.

### ISSUE THREAD

**Issue by npalm** [philips-labs/dct-notary-admin#169]
GitHub Actions is deprecating `set-env` and `add-path` commands. Check out this [blog post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for more details.

This repository has been listed by a scan that it uses one of de deprecated actions. It could be case the commands are directly usages in the build yaml, or indirect via an action. Action runners above version 2.273.5 will warn for usages of these deprecated commands. Expectation is that the commands will be disabled before the end of the year.

Please check your build YAML and action log to ensure your build keep working once the commands are disabled.

Feel free to reach out if you question or any help is needed

Regards, Niek Palm (@npalm)

`this issue is generated based on a scan`

**Comment by marcofranssen** [comment]
Based on what hit did this repo show up in the scan? I don't see where the issue would be in the workflow on this repo.

**Comment by npalm** [comment]
We have gotten a message from GitHub, did you check the pipeline log? Also action can cause the issue.

**Comment by npalm** [comment]
Already solved https://github.com/philips-labs/dct-notary-admin/runs/1358482534?check_suite_focus=true#step:3:1

**Comment by marcofranssen** [comment]
For tracing. This dependabot PR https://github.com/philips-labs/dct-notary-admin/pull/167 resolved the issue.

The github action here has updated its own dependencies this PR https://github.com/innovationnorway/setup-vault/pull/73 on the action itself. It updates specifically `@actions/core` to the patched version.
